### ISSUE TITLE
Coin icon covering text

### ISSUE THREAD

**Issue by LiviiYS** [glisco03/numismatic-overhaul#108]
When using numismatic with modernui the coin icon partially covers the number,

![2023-10-18_18 29 05](https://github.com/wisp-forest/numismatic-overhaul/assets/72738254/8c1675bc-8fc4-42dc-8ab9-c60eb0ad8e03)

**Comment by gliscowo** [comment]
Unfortunately I don't think this issue is a great concern for us, given that ModernUI explicitly causes it - please report it to them instead. This is also more likely to lead to a solution, as they will be much more familiar with the modifications they make to text rendering code, whereas we would need to first reverse-engineer their implementation

I'll leave this issue open for now until we hear from them, but we won't be actively looking into it

Cheers

**Comment by BloCamLimb** [comment]
This is a common problem, your code assumes incorrect text layout:
https://github.com/wisp-forest/numismatic-overhaul/blob/a5b5078371d4050a4a38e099217f43226cddf344/src/main/java/com/glisco/numismaticoverhaul/client/gui/CurrencyTooltipRenderer.java#L53-L56
Modern UI has a Complex Text Layout Engine, the width of space characters depends on FreeType scaler and TrueType designer, and it's context-aware. Thus, you may write a helper method kinda like this, if you want to provide reliable indentation:

```java
// in yarn namespace
static String indentation(TextRenderer tr, int indent) {
    var str = " ";
    while (tr.getWidth(str) < indent) str += " ";
    return str;
}
```
Notably, you shouldn't measure a single space character and do division. Firstly, `getWidth` returns the ceiling of string width. Secondly, text layout is context-aware, it's not linear.
But you can cache this indentation string after a resource reload on *main* thread, to deal with font changes, via `net.fabricmc.fabric.api.resource.SimpleResourceReloadListener#apply`

**Comment by Noaaan** [comment]
Fixed as of 0.2.12 for 1.20.1 and 1.20.2

**Comment by 46-LMi** [comment]
Hi bro, this bug is still not fixed
I'm playing 1.20.1 with this mod version 0.2.18 on fabric

**Comment by Noaaan** [comment]
This issue was most definitely fixed. If you are experiencing a similar issue (even with the same mods), please open a new issue. 
@46-LMi
